[project]
name = "Pukaar"
version = "0.1.0"
description = "Pukaar MVP"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlmodel",
    "pydantic",
    "pillow",
    "python-multipart",
    "httpx",
    "orjson",
    "faster-whisper",
    "lxml"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
