"""A calm ambient music bed for the videos, synthesised from scratch (no samples, no third-party audio).

usage: python3 music.py seconds out.wav [seed]
Writes a 48 kHz stereo float wav at least `seconds` long: soft additive pads over a slow four-chord loop, a sine
sub-bass, a sparse plucked arpeggio with a ping-pong delay, a little filtered air, all through a synthetic reverb.
Same seed and length, same file. The result is original work generated by this script, dedicated to the public
domain under CC0 1.0 (docs/media/CREDITS.md). Loudness is set later, in mix.py, where the bed is ducked under the
voice.
"""
import sys
import numpy as np
import soundfile as sf
from scipy.signal import butter, sosfilt, oaconvolve

SR = 48000
dur = float(sys.argv[1]) + 4.0
out = sys.argv[2]
seed = int(sys.argv[3]) if len(sys.argv) > 3 else 7
rng = np.random.default_rng(seed)
n = int(dur * SR)
t = np.arange(n) / SR


def hz(midi):
    return 440.0 * 2 ** ((midi - 69) / 12)


# D major, slow and open: Dmaj9, Bm11, Gmaj9, A6sus2 (MIDI notes, low to high)
CHORDS = [
    [50, 57, 61, 64, 66],  # D3 A3 C#4 E4 F#4
    [47, 54, 57, 61, 64],  # B2 F#3 A3 C#4 E4
    [43, 50, 54, 57, 59],  # G2 D3 F#3 A3 B3
    [45, 52, 54, 59, 61],  # A2 E3 F#3 B3 C#4
]
CHORD_S = 9.6  # four bars at 100 bpm
BEAT = 60 / 100

L = np.zeros(n, dtype=np.float64)
R = np.zeros(n, dtype=np.float64)


def pad_note(f0, a, b, pan, detune_cents=6.0):
    """An additive, slightly detuned pad note from sample a to b, with long attack and release."""
    att, rel = int(2.4 * SR), int(3.2 * SR)
    a0, b1 = max(0, a - att // 2), min(n, b + rel)
    tt = t[a0:b1]
    sig = np.zeros(len(tt))
    for k in range(1, 9):
        amp = (1.0 / k) * np.exp(-k / 2.6)
        for d in (-detune_cents, detune_cents):
            f = f0 * k * 2 ** (d / 1200)
            if f > 5000:
                continue
            sig += amp * np.sin(2 * np.pi * f * tt + rng.uniform(0, 2 * np.pi))
    env = np.ones(len(tt))
    up = min(att, len(tt))
    env[:up] = np.sin(np.linspace(0, np.pi / 2, up)) ** 2
    down = min(rel, len(tt))
    env[-down:] *= np.cos(np.linspace(0, np.pi / 2, down)) ** 2
    # slow swell so the pad breathes
    env *= 0.85 + 0.15 * np.sin(2 * np.pi * tt / 7.3 + rng.uniform(0, 6.28))
    sig *= env
    L[a0:b1] += sig * np.cos(pan * np.pi / 2)
    R[a0:b1] += sig * np.sin(pan * np.pi / 2)


def pluck(f0, a, level, pan):
    """A soft plucked sine (fundamental plus a quiet octave) with an exponential decay."""
    ln = int(1.8 * SR)
    b = min(n, a + ln)
    tt = np.arange(b - a) / SR
    env = np.exp(-tt / 0.45) * (1 - np.exp(-tt / 0.004))
    sig = level * env * (np.sin(2 * np.pi * f0 * tt) + 0.18 * np.sin(4 * np.pi * f0 * tt))
    L[a:b] += sig * np.cos(pan * np.pi / 2)
    R[a:b] += sig * np.sin(pan * np.pi / 2)


i = 0
start = 0.0
while start < dur:
    chord = CHORDS[i % len(CHORDS)]
    a, b = int(start * SR), int(min(dur, start + CHORD_S) * SR)
    for j, m in enumerate(chord):
        pad_note(hz(m), a, b, pan=0.25 + 0.5 * j / (len(chord) - 1))
    # sub-bass on the root
    root = hz(chord[0] - 12)
    a0, b1 = a, min(n, b + int(1.5 * SR))
    tt = t[a0:b1]
    env = np.minimum(1, (tt - tt[0]) / 1.2) * np.minimum(1, np.maximum(0, (tt[-1] - tt) / 1.5))
    sub = 0.55 * env * np.sin(2 * np.pi * root * tt)
    L[a0:b1] += sub
    R[a0:b1] += sub
    # sparse arpeggio, an octave up, on quarter notes with gaps
    tones = [m + 12 for m in chord[1:]]
    for q in range(int(CHORD_S / BEAT)):
        if rng.random() < 0.42:
            when = start + q * BEAT
            if when < dur - 1:
                pluck(hz(tones[rng.integers(len(tones))]), int(when * SR), 0.22, pan=rng.uniform(0.2, 0.8))
    start += CHORD_S
    i += 1

# ping-pong delay on everything (dotted eighth), quiet
d = int(BEAT * 0.75 * SR)
for k, g in enumerate([0.22, 0.14, 0.08]):
    s = d * (k + 1)
    if k % 2 == 0:
        L[s:] += g * R[:-s]
    else:
        R[s:] += g * L[:-s]

# air: band-passed noise, very low
air = rng.standard_normal(n)
air = sosfilt(butter(2, [2500, 7000], btype="band", fs=SR, output="sos"), air) * 0.012
air *= 0.6 + 0.4 * np.sin(2 * np.pi * t / 11.0)
L += air
R += np.roll(air, 977)

# keep it soft: low-pass the whole bed, then a synthetic stereo reverb
lp = butter(2, 3800, btype="low", fs=SR, output="sos")
L, R = sosfilt(lp, L), sosfilt(lp, R)
ir_n = int(3.6 * SR)
ti = np.arange(ir_n) / SR
irL = rng.standard_normal(ir_n) * np.exp(-ti / 0.9)
irR = rng.standard_normal(ir_n) * np.exp(-ti / 0.9)
irL = sosfilt(butter(1, 3000, btype="low", fs=SR, output="sos"), irL)
irR = sosfilt(butter(1, 3000, btype="low", fs=SR, output="sos"), irR)
irL /= np.sqrt((irL**2).sum())
irR /= np.sqrt((irR**2).sum())
wetL = oaconvolve(L, irL)[:n]
wetR = oaconvolve(R, irR)[:n]
L = 0.55 * L + 0.45 * wetL
R = 0.55 * R + 0.45 * wetR
# remove DC and rumble
hp = butter(2, 35, btype="high", fs=SR, output="sos")
L, R = sosfilt(hp, L), sosfilt(hp, R)
y = np.stack([L, R], axis=1)
y /= np.abs(y).max() + 1e-9
y *= 0.5
sf.write(out, y.astype(np.float32), SR, subtype="FLOAT")
print(f"music: {dur:.1f} s, seed {seed} -> {out}")
