#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="$ROOT_DIR/backend"
HOST="${PUKAAR_API_HOST:-0.0.0.0}"
PORT="${PUKAAR_API_PORT:-8000}"

export PUKAAR_NODE_PROFILE="${PUKAAR_NODE_PROFILE:-raspberry-pi-16gb-multimodal-prod}"
export PUKAAR_DATA_DIR="${PUKAAR_DATA_DIR:-/mnt/pukaar/data}"
export PUKAAR_NODE_PROVIDER="${PUKAAR_NODE_PROVIDER:-litert}"
export PUKAAR_NODE_MODEL_PATH="${PUKAAR_NODE_MODEL_PATH:-$BACKEND_DIR/data/models/pukaar-model-2b.litertlm}"
export PUKAAR_NODE_BACKEND="${PUKAAR_NODE_BACKEND:-gpu}"
export PUKAAR_NODE_MULTIMODAL_BACKEND="${PUKAAR_NODE_MULTIMODAL_BACKEND:-cpu}"
export PUKAAR_NODE_MULTIMODAL_VISION_BACKEND="${PUKAAR_NODE_MULTIMODAL_VISION_BACKEND:-cpu}"
export PUKAAR_NODE_CACHE_DIR="${PUKAAR_NODE_CACHE_DIR:-$BACKEND_DIR/data/litert-cache}"
export PUKAAR_NODE_ENABLE_SPECULATIVE_DECODING="${PUKAAR_NODE_ENABLE_SPECULATIVE_DECODING:-true}"
export PUKAAR_NODE_MAX_OUTPUT_TOKENS="${PUKAAR_NODE_MAX_OUTPUT_TOKENS:-1024}"
export PUKAAR_NODE_MULTIMODAL_MAX_OUTPUT_TOKENS="${PUKAAR_NODE_MULTIMODAL_MAX_OUTPUT_TOKENS:-2048}"
export PUKAAR_LLM_ENABLED="${PUKAAR_LLM_ENABLED:-false}"
export PUKAAR_LLM_BASE_URL="${PUKAAR_LLM_BASE_URL:-http://127.0.0.1:11434/v1}"
export PUKAAR_LLM_MODEL="${PUKAAR_LLM_MODEL:-pukaar-model:2b}"
export PUKAAR_LLM_API_KEY="${PUKAAR_LLM_API_KEY:-ollama}"

export PUKAAR_MULTIMODAL_ENABLED="${PUKAAR_MULTIMODAL_ENABLED:-true}"
export PUKAAR_MULTIMODAL_VERIFIER_ENABLED="${PUKAAR_MULTIMODAL_VERIFIER_ENABLED:-false}"
export PUKAAR_MULTIMODAL_BASE_URL="${PUKAAR_MULTIMODAL_BASE_URL:-$PUKAAR_LLM_BASE_URL}"
export PUKAAR_MULTIMODAL_MODEL="${PUKAAR_MULTIMODAL_MODEL:-pukaar-model-2b.litertlm}"
export PUKAAR_MULTIMODAL_MAX_FRAMES="${PUKAAR_MULTIMODAL_MAX_FRAMES:-4}"
export PUKAAR_MULTIMODAL_FRAME_SAMPLE_SECONDS="${PUKAAR_MULTIMODAL_FRAME_SAMPLE_SECONDS:-60}"
export PUKAAR_MULTIMODAL_IMAGE_MAX_SIDE="${PUKAAR_MULTIMODAL_IMAGE_MAX_SIDE:-960}"
export PUKAAR_MULTIMODAL_NUM_CTX="${PUKAAR_MULTIMODAL_NUM_CTX:-4096}"
export PUKAAR_MULTIMODAL_NUM_PREDICT="${PUKAAR_MULTIMODAL_NUM_PREDICT:-512}"
export PUKAAR_MULTIMODAL_TIMEOUT_SECONDS="${PUKAAR_MULTIMODAL_TIMEOUT_SECONDS:-240}"

export PUKAAR_MAX_CURATED_FRAMES="${PUKAAR_MAX_CURATED_FRAMES:-4}"
export PUKAAR_ARTIFACT_RETENTION_DAYS="${PUKAAR_ARTIFACT_RETENTION_DAYS:-14}"

cd "$BACKEND_DIR"
if [[ -d ".venv" ]]; then
  # shellcheck disable=SC1091
  source ".venv/bin/activate"
else
  echo "Missing backend virtualenv at $BACKEND_DIR/.venv" >&2
  exit 1
fi

python3 "$ROOT_DIR/scripts/fetch_litert_model.py"
python3 "$ROOT_DIR/scripts/fetch_demo_assets.py"
PYTHONPATH=src python3 -m Pukaar.scripts.seed
PYTHONPATH=src python3 -m uvicorn Pukaar.main:app --host "$HOST" --port "$PORT"
